# Use an official Node.js runtime as a parent image for the build stage
FROM node:14 as build

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the application
RUN npm run build

# Use nginx as the parent image for the runtime stage
FROM nginx:latest

# Copy the Nginx configuration file to the image
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the built application from the build stage to the nginx html directory
COPY --from=build /app/dist/frontend /usr/share/nginx/html

# Expose port 4200 for the application
EXPOSE 4200

# Start nginx
CMD ["nginx", "-g", "daemon off;"]